count:
  max: '360'
  min: '360'
  note: count of data to use per training
  value: '360'
extra_datas:
  max: '60'
  min: '60'
  note: count of extra data to use per visualiza
  value: '60'
max_dt:
  note: end of the data
  value: '20250120'
min_dt:
  note: start of the data
  value: '20160711'
stock_code_path:
  note: the path of folder where the data is located
  value: API/datas
stock_codes:
- 005930
- '000660'
- 083650
- '010120'
- '035720'
- '012450'
- 098460
- '064350'
- 056080
- 068270
- 039030
- 124500
stock_columns:
- stck_clpr
- stck_hgpr
- stck_lwpr
- acml_vol
- prdy_vrss
- '5'
- '20'
- '60'
- rsi
- bb_upper
- bb_lower
visualization_columns:
- stck_clpr
- acml_vol
- '5'
- '20'
- '60'
- rsi
- bb_upper
- bb_lower
visualization_format:
  note: visualization image format for extra datas
  value: GASF
