stock_codes:
- 005930
- '000660'
- 083650
- '010120'
- '035720'
- '012450'
- 098460
- '064350'
- 056080
- 068270
- 039030
- 124500
stock_columns:
- stck_clpr
- stck_hgpr
- stck_lwpr
- acml_vol
- prdy_vrss
- '5'
- '20'
- '60'
- rsi
- bb_upper
- bb_lower
stock_code_path:
  max: None
  min: None
  note: the path of folder where the data is located
  value: API/datas
max_dt:
  max: None
  min: None
  note: end of the data
  value: '20250120'
min_dt:
  max: None
  min: None
  note: start of the data
  value: '20160711'
count:
  max: '360'
  min: '360'
  note: count of data to use per training
  value: '360'